socket_params:                 # Параметры подключения к роботу
  IP_ADDRESS: '192.168.0.1'        # IP SocketServer
  PORT: 80                         # Порт SocketServer
  enable: 1                        # Отк./вкл. для тестирования (0/1) чтобы не производилось подключение к роботу

camera:                        # Параметры камеры
  online: 1                        # Переключение на подгрузку кадров из видео-записьи/трансляцитю с камеры (0/1)
  H: 250.0                         # Высота от поля до камеры
  h: 24.3                          # Высота препятствия
  sharpening: 0                    # Повышение резкости (вкл. при проблемах с фокусом на камере)
  equalize_hist: 1                 # Выравнивание гистограммы
  cam_shape_width: 640            # Разрешение камеры (по умолчанию 1280)
  cam_shape_height: 480           # Разрешение камеры (по умолчанию 720)

map_params:                    # Параметры полигона
  resolution: 2200                 # Размер поля в мм (по краям калибровочных ArUco маркеров)

aruco:                         # Очерёдность размещения ArUco маркеров на полигоне
  left_up: 0                       # Левый верхний
  right_up: 5                      # Правый верхний
  right_down: 3                    # Правый нижний
  left_down: 4                     # Левый нижний

# aruco:                         # Очерёдность размещения ArUco маркеров на полигоне
#   left_up: 5                       # Левый верхний
#   right_up: 3                      # Правый верхний
#   right_down: 0                    # Правый нижний
#   left_down: 4                     # Левый нижний

move:                          # Параметры движения работа
  dist_stop: 50                    # Расстояние для остановки при движении к точке (мм)
  max_speed: 0.08                  # Максимальная скорость Robotino (м/с)
  k_prop: 1.0                      # Пропорциональный коэффициент
  filter_gain: 0.2                 # Коэффициент фильтрации скорости

grid:                          # Параметры для сетки при планировании
  step: 44                         # Шаг дискретизации пикселей n*px/px (22, 44, 55, 110, 220, 440) желательно выбирать кратно размеру поля
  robot_radius: 275                # Радиус робота (+ допуск из-за искажений камеры при проецировании)
  WALL_WIDTH: 150                  # Толщина стенки по контуру рабочего поля (для 1 задачи)

utils:
  log_dir: "logs/"                 # Путь к папке с логами
  video_path: "video/vid.mp4"      # Путь к видео при отключении online в camera