socket_params:                 # Параметры подключения к роботу
  IP_ADDRESS: '192.168.0.1'        # IP SocketServer
  PORT: 80                         # Порт SocketServer
  enable: 0                        # Отк./вкл. для тестирования (0/1) чтобы не производилось подключение к роботу

map_params:                    # Параметры полигона
  resolution: 2200                 # Размер поля в мм (по краям калибровочных ArUco маркеров)

aruco:                         # Очерёдность размещения ArUco маркеров на полигоне
  left_up: 0                       # Левый верхний
  right_up: 5                      # Правый верхний
  right_down: 3                    # Правый нижний
  left_down: 4                     # Левый нижний

camera:                        # Параметры камеры
  online: 0                        # Переключение на подгрузку кадров из видео-записьи/трансляцитю с камеры (0/1)
  H: 250.0                         # Высота от поля до камеры
  h: 24.3                          # Высота препятствия
  sharpening: 1                    # Повышение резкости (вкл. при проблемах с фокусом на камере)

move:                          # Параметры движения работа
  dist_stop: 50                    # Расстояние для остановки при движении к точке (мм)
  max_speed: 0.08                  # Максимальная скорость Robotino (м/с)
  k_prop: 1.0                      # Пропорциональный коэффициент 
  
apf:                           # Параметры для потеницального поля Atrificial Potential Field
  d0: 100                          # Радиус влияния препятствия (px)
  influence_radius: 390            # Радиус влияния препятствия (px)
  scale_factor: 1                  # Коэффициент уменьшения изображения (для ускорения вычислений при необходимости [0-1])
  WALL_WIDTH: 1                    # Толщина стенки по контуру рабочего поля (для 1 задачи)
  WALL_WIDTH2: 150                 # Толщина стенки по контуру рабочего поля (для 2-3 задачи)
  k_rep: 4.0e-9                    # Коэффициент отталкивания

grid:                          # Параметры для сетки при планировании
  step: 44                         # Шаг дискретизации пикселей n*px/px (22, 44, 55, 110, 220, 440) желательно выбирать кратно размеру поля
  robot_radius: 285                # Радиус робота (+ допуск из-за искажений камеры при проецировании)

utils:
  log_dir: "logs/"                 # Путь к папке с логами
  video_path: "video/vid.mp4"       # Путь к видео при отключении online в camera